# Generated by Django 3.0.9 on 2021-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chess',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=7)),
            ],
        ),
    ]
